# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobel_viewer.ui'
#
# Created: Tue Jul 22 18:17:11 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GemVisualGUI(object):
    def setupUi(self, GemVisualGUI):
        GemVisualGUI.setObjectName(_fromUtf8("GemVisualGUI"))
        GemVisualGUI.resize(1388, 1028)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/chart_line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GemVisualGUI.setWindowIcon(icon)
        GemVisualGUI.setAutoFillBackground(True)
        GemVisualGUI.setStyleSheet(_fromUtf8("c"))
        GemVisualGUI.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(GemVisualGUI)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.frame_2 = QtGui.QFrame(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_profilesControl = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_profilesControl.setFont(font)
        self.label_profilesControl.setObjectName(_fromUtf8("label_profilesControl"))
        self.verticalLayout_15.addWidget(self.label_profilesControl)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gemYearLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gemYearLabel.setFont(font)
        self.gemYearLabel.setObjectName(_fromUtf8("gemYearLabel"))
        self.horizontalLayout.addWidget(self.gemYearLabel)
        self.timeSeriesComboBox = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSeriesComboBox.sizePolicy().hasHeightForWidth())
        self.timeSeriesComboBox.setSizePolicy(sizePolicy)
        self.timeSeriesComboBox.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeSeriesComboBox.setFont(font)
        self.timeSeriesComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeSeriesComboBox.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.timeSeriesComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.timeSeriesComboBox.setObjectName(_fromUtf8("timeSeriesComboBox"))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.timeSeriesComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.timeSeriesComboBox)
        self.pointInTime_label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pointInTime_label.setFont(font)
        self.pointInTime_label.setObjectName(_fromUtf8("pointInTime_label"))
        self.horizontalLayout.addWidget(self.pointInTime_label)
        self.loadMaskButton = QtGui.QToolButton(self.frame_2)
        self.loadMaskButton.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loadMaskButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/folder_image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadMaskButton.setIcon(icon1)
        self.loadMaskButton.setCheckable(True)
        self.loadMaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.loadMaskButton.setObjectName(_fromUtf8("loadMaskButton"))
        self.horizontalLayout.addWidget(self.loadMaskButton)
        self.applyMask = QtGui.QToolButton(self.frame_2)
        self.applyMask.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.applyMask.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/shape_move_forwards.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyMask.setIcon(icon2)
        self.applyMask.setIconSize(QtCore.QSize(24, 24))
        self.applyMask.setCheckable(True)
        self.applyMask.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.applyMask.setObjectName(_fromUtf8("applyMask"))
        self.horizontalLayout.addWidget(self.applyMask)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_SPOT = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_SPOT.setFont(font)
        self.label_SPOT.setObjectName(_fromUtf8("label_SPOT"))
        self.verticalLayout_14.addWidget(self.label_SPOT)
        self.frameTimeSlide = QtGui.QFrame(self.frame_2)
        self.frameTimeSlide.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTimeSlide.sizePolicy().hasHeightForWidth())
        self.frameTimeSlide.setSizePolicy(sizePolicy)
        self.frameTimeSlide.setFrameShape(QtGui.QFrame.Box)
        self.frameTimeSlide.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameTimeSlide.setObjectName(_fromUtf8("frameTimeSlide"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frameTimeSlide)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.timeSlider = QtGui.QSlider(self.frameTimeSlide)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSlider.sizePolicy().hasHeightForWidth())
        self.timeSlider.setSizePolicy(sizePolicy)
        self.timeSlider.setMinimumSize(QtCore.QSize(615, 21))
        self.timeSlider.setMaximumSize(QtCore.QSize(1137, 21))
        self.timeSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.timeSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeSlider.setStyleSheet(_fromUtf8(""))
        self.timeSlider.setMaximum(35)
        self.timeSlider.setSliderPosition(0)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setInvertedControls(False)
        self.timeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.timeSlider.setTickInterval(3)
        self.timeSlider.setObjectName(_fromUtf8("timeSlider"))
        self.verticalLayout_8.addWidget(self.timeSlider)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(5, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.apr_label = QtGui.QLabel(self.frameTimeSlide)
        self.apr_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.apr_label.setFont(font)
        self.apr_label.setScaledContents(False)
        self.apr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.apr_label.setWordWrap(False)
        self.apr_label.setObjectName(_fromUtf8("apr_label"))
        self.gridLayout.addWidget(self.apr_label, 0, 1, 1, 1)
        self.may_label = QtGui.QLabel(self.frameTimeSlide)
        self.may_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.may_label.setFont(font)
        self.may_label.setScaledContents(False)
        self.may_label.setAlignment(QtCore.Qt.AlignCenter)
        self.may_label.setWordWrap(False)
        self.may_label.setObjectName(_fromUtf8("may_label"))
        self.gridLayout.addWidget(self.may_label, 0, 2, 1, 1)
        self.jun_label = QtGui.QLabel(self.frameTimeSlide)
        self.jun_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.jun_label.setFont(font)
        self.jun_label.setScaledContents(False)
        self.jun_label.setAlignment(QtCore.Qt.AlignCenter)
        self.jun_label.setWordWrap(False)
        self.jun_label.setObjectName(_fromUtf8("jun_label"))
        self.gridLayout.addWidget(self.jun_label, 0, 3, 1, 1)
        self.jul_label = QtGui.QLabel(self.frameTimeSlide)
        self.jul_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.jul_label.setFont(font)
        self.jul_label.setScaledContents(False)
        self.jul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.jul_label.setWordWrap(False)
        self.jul_label.setObjectName(_fromUtf8("jul_label"))
        self.gridLayout.addWidget(self.jul_label, 0, 4, 1, 1)
        self.ago_label = QtGui.QLabel(self.frameTimeSlide)
        self.ago_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ago_label.setFont(font)
        self.ago_label.setScaledContents(False)
        self.ago_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ago_label.setWordWrap(False)
        self.ago_label.setObjectName(_fromUtf8("ago_label"))
        self.gridLayout.addWidget(self.ago_label, 0, 5, 1, 1)
        self.sep_label = QtGui.QLabel(self.frameTimeSlide)
        self.sep_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.sep_label.setFont(font)
        self.sep_label.setScaledContents(False)
        self.sep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sep_label.setWordWrap(False)
        self.sep_label.setObjectName(_fromUtf8("sep_label"))
        self.gridLayout.addWidget(self.sep_label, 0, 6, 1, 1)
        self.oct_label = QtGui.QLabel(self.frameTimeSlide)
        self.oct_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.oct_label.setFont(font)
        self.oct_label.setScaledContents(False)
        self.oct_label.setAlignment(QtCore.Qt.AlignCenter)
        self.oct_label.setWordWrap(False)
        self.oct_label.setObjectName(_fromUtf8("oct_label"))
        self.gridLayout.addWidget(self.oct_label, 0, 7, 1, 1)
        self.nov_label = QtGui.QLabel(self.frameTimeSlide)
        self.nov_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.nov_label.setFont(font)
        self.nov_label.setScaledContents(False)
        self.nov_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nov_label.setWordWrap(False)
        self.nov_label.setObjectName(_fromUtf8("nov_label"))
        self.gridLayout.addWidget(self.nov_label, 0, 8, 1, 1)
        self.dec_label = QtGui.QLabel(self.frameTimeSlide)
        self.dec_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dec_label.setFont(font)
        self.dec_label.setScaledContents(False)
        self.dec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dec_label.setWordWrap(False)
        self.dec_label.setObjectName(_fromUtf8("dec_label"))
        self.gridLayout.addWidget(self.dec_label, 0, 9, 1, 1)
        self.jan_label = QtGui.QLabel(self.frameTimeSlide)
        self.jan_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.jan_label.setFont(font)
        self.jan_label.setScaledContents(False)
        self.jan_label.setAlignment(QtCore.Qt.AlignCenter)
        self.jan_label.setWordWrap(False)
        self.jan_label.setObjectName(_fromUtf8("jan_label"))
        self.gridLayout.addWidget(self.jan_label, 0, 10, 1, 1)
        self.feb_label = QtGui.QLabel(self.frameTimeSlide)
        self.feb_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.feb_label.setFont(font)
        self.feb_label.setScaledContents(False)
        self.feb_label.setAlignment(QtCore.Qt.AlignCenter)
        self.feb_label.setWordWrap(False)
        self.feb_label.setObjectName(_fromUtf8("feb_label"))
        self.gridLayout.addWidget(self.feb_label, 0, 11, 1, 1)
        self.mar_label = QtGui.QLabel(self.frameTimeSlide)
        self.mar_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.mar_label.setFont(font)
        self.mar_label.setScaledContents(False)
        self.mar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mar_label.setWordWrap(False)
        self.mar_label.setObjectName(_fromUtf8("mar_label"))
        self.gridLayout.addWidget(self.mar_label, 0, 12, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 13, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.lockButton = QtGui.QToolButton(self.frameTimeSlide)
        self.lockButton.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lockButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/lock_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/lock.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lockButton.setIcon(icon3)
        self.lockButton.setCheckable(True)
        self.lockButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.lockButton.setObjectName(_fromUtf8("lockButton"))
        self.horizontalLayout_2.addWidget(self.lockButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_14.addWidget(self.frameTimeSlide)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.splitter_2 = QtGui.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 550))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.leftTabWidget = QtGui.QTabWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.leftTabWidget.setFont(font)
        self.leftTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.leftTabWidget.setObjectName(_fromUtf8("leftTabWidget"))
        self.plotViewerTab = QtGui.QWidget()
        self.plotViewerTab.setObjectName(_fromUtf8("plotViewerTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.plotViewerTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dockPlotWidget = QtGui.QDockWidget(self.plotViewerTab)
        self.dockPlotWidget.setMinimumSize(QtCore.QSize(450, 459))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dockPlotWidget.setFont(font)
        self.dockPlotWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockPlotWidget.setObjectName(_fromUtf8("dockPlotWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnZoomPlot = QtGui.QToolButton(self.dockWidgetContents)
        self.btnZoomPlot.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnZoomPlot.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomPlot.setIcon(icon4)
        self.btnZoomPlot.setIconSize(QtCore.QSize(24, 24))
        self.btnZoomPlot.setCheckable(True)
        self.btnZoomPlot.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnZoomPlot.setObjectName(_fromUtf8("btnZoomPlot"))
        self.horizontalLayout_5.addWidget(self.btnZoomPlot)
        self.gemClassLabel = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gemClassLabel.setFont(font)
        self.gemClassLabel.setObjectName(_fromUtf8("gemClassLabel"))
        self.horizontalLayout_5.addWidget(self.gemClassLabel)
        self.gemClassSpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gemClassSpinBox.setFont(font)
        self.gemClassSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gemClassSpinBox.setMinimum(0)
        self.gemClassSpinBox.setMaximum(86)
        self.gemClassSpinBox.setProperty("value", 0)
        self.gemClassSpinBox.setObjectName(_fromUtf8("gemClassSpinBox"))
        self.horizontalLayout_5.addWidget(self.gemClassSpinBox)
        spacerItem5 = QtGui.QSpacerItem(468, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.plotWidgetHolder = QtGui.QWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidgetHolder.sizePolicy().hasHeightForWidth())
        self.plotWidgetHolder.setSizePolicy(sizePolicy)
        self.plotWidgetHolder.setMinimumSize(QtCore.QSize(0, 375))
        self.plotWidgetHolder.setObjectName(_fromUtf8("plotWidgetHolder"))
        self.verticalLayout.addWidget(self.plotWidgetHolder)
        self.dockPlotWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout_2.addWidget(self.dockPlotWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/chart_curve.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftTabWidget.addTab(self.plotViewerTab, icon5, _fromUtf8(""))
        self.rightTabWidget = QtGui.QTabWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rightTabWidget.setFont(font)
        self.rightTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.rightTabWidget.setObjectName(_fromUtf8("rightTabWidget"))
        self.imageViewerTab = QtGui.QWidget()
        self.imageViewerTab.setObjectName(_fromUtf8("imageViewerTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.imageViewerTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.dockImageWidget = QtGui.QDockWidget(self.imageViewerTab)
        self.dockImageWidget.setMinimumSize(QtCore.QSize(450, 486))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dockImageWidget.setFont(font)
        self.dockImageWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockImageWidget.setObjectName(_fromUtf8("dockImageWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pointInTime = QtGui.QLineEdit(self.dockWidgetContents_2)
        self.pointInTime.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointInTime.sizePolicy().hasHeightForWidth())
        self.pointInTime.setSizePolicy(sizePolicy)
        self.pointInTime.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pointInTime.setFont(font)
        self.pointInTime.setMouseTracking(False)
        self.pointInTime.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pointInTime.setAcceptDrops(False)
        self.pointInTime.setFrame(True)
        self.pointInTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pointInTime.setObjectName(_fromUtf8("pointInTime"))
        self.horizontalLayout_6.addWidget(self.pointInTime)
        spacerItem6 = QtGui.QSpacerItem(498, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.imageWidgetHolder = QtGui.QWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageWidgetHolder.sizePolicy().hasHeightForWidth())
        self.imageWidgetHolder.setSizePolicy(sizePolicy)
        self.imageWidgetHolder.setMinimumSize(QtCore.QSize(0, 405))
        self.imageWidgetHolder.setObjectName(_fromUtf8("imageWidgetHolder"))
        self.verticalLayout_3.addWidget(self.imageWidgetHolder)
        self.dockImageWidget.setWidget(self.dockWidgetContents_2)
        self.verticalLayout_4.addWidget(self.dockImageWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTabWidget.addTab(self.imageViewerTab, icon6, _fromUtf8(""))
        self.freqViewerTab = QtGui.QWidget()
        self.freqViewerTab.setObjectName(_fromUtf8("freqViewerTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.freqViewerTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.dockFreqWidget = QtGui.QDockWidget(self.freqViewerTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dockFreqWidget.setFont(font)
        self.dockFreqWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockFreqWidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockFreqWidget.setObjectName(_fromUtf8("dockFreqWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.binSpinBox = QtGui.QSpinBox(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.binSpinBox.setFont(font)
        self.binSpinBox.setMinimum(2)
        self.binSpinBox.setMaximum(50)
        self.binSpinBox.setSingleStep(1)
        self.binSpinBox.setProperty("value", 10)
        self.binSpinBox.setObjectName(_fromUtf8("binSpinBox"))
        self.horizontalLayout_8.addWidget(self.binSpinBox)
        spacerItem7 = QtGui.QSpacerItem(38, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.freqWidgetHolder = QtGui.QWidget(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqWidgetHolder.sizePolicy().hasHeightForWidth())
        self.freqWidgetHolder.setSizePolicy(sizePolicy)
        self.freqWidgetHolder.setMinimumSize(QtCore.QSize(0, 375))
        self.freqWidgetHolder.setObjectName(_fromUtf8("freqWidgetHolder"))
        self.verticalLayout_5.addWidget(self.freqWidgetHolder)
        self.dockFreqWidget.setWidget(self.dockWidgetContents_3)
        self.verticalLayout_7.addWidget(self.dockFreqWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/chart_bar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTabWidget.addTab(self.freqViewerTab, icon7, _fromUtf8(""))
        self.statsTabWidget = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsTabWidget.sizePolicy().hasHeightForWidth())
        self.statsTabWidget.setSizePolicy(sizePolicy)
        self.statsTabWidget.setMinimumSize(QtCore.QSize(0, 225))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statsTabWidget.setFont(font)
        self.statsTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.statsTabWidget.setObjectName(_fromUtf8("statsTabWidget"))
        self.logTabDisplay = QtGui.QWidget()
        self.logTabDisplay.setObjectName(_fromUtf8("logTabDisplay"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.logTabDisplay)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.textDisplay = QtGui.QTextEdit(self.logTabDisplay)
        self.textDisplay.setObjectName(_fromUtf8("textDisplay"))
        self.verticalLayout_6.addWidget(self.textDisplay)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/book_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statsTabWidget.addTab(self.logTabDisplay, icon8, _fromUtf8(""))
        self.simTestTab = QtGui.QWidget()
        self.simTestTab.setObjectName(_fromUtf8("simTestTab"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.simTestTab)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.simTestDockWidget = QtGui.QDockWidget(self.simTestTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simTestDockWidget.sizePolicy().hasHeightForWidth())
        self.simTestDockWidget.setSizePolicy(sizePolicy)
        self.simTestDockWidget.setMinimumSize(QtCore.QSize(1030, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.simTestDockWidget.setFont(font)
        self.simTestDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.simTestDockWidget.setObjectName(_fromUtf8("simTestDockWidget"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.controlSimTestDockWidget = QtGui.QDockWidget(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlSimTestDockWidget.sizePolicy().hasHeightForWidth())
        self.controlSimTestDockWidget.setSizePolicy(sizePolicy)
        self.controlSimTestDockWidget.setMinimumSize(QtCore.QSize(500, 146))
        self.controlSimTestDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.controlSimTestDockWidget.setObjectName(_fromUtf8("controlSimTestDockWidget"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.testComboBox = QtGui.QComboBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testComboBox.setFont(font)
        self.testComboBox.setObjectName(_fromUtf8("testComboBox"))
        self.testComboBox.addItem(_fromUtf8(""))
        self.testComboBox.addItem(_fromUtf8(""))
        self.testComboBox.addItem(_fromUtf8(""))
        self.testComboBox.addItem(_fromUtf8(""))
        self.testComboBox.addItem(_fromUtf8(""))
        self.testComboBox.addItem(_fromUtf8(""))
        self.testComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.testComboBox)
        spacerItem8 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_10.addWidget(self.label_2)
        self.pValueSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pValueSpinBox.setFont(font)
        self.pValueSpinBox.setMaximum(1.0)
        self.pValueSpinBox.setSingleStep(0.01)
        self.pValueSpinBox.setProperty("value", 0.95)
        self.pValueSpinBox.setObjectName(_fromUtf8("pValueSpinBox"))
        self.horizontalLayout_10.addWidget(self.pValueSpinBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.byPairedClassesCheckBox = QtGui.QCheckBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.byPairedClassesCheckBox.setFont(font)
        self.byPairedClassesCheckBox.setAutoExclusive(True)
        self.byPairedClassesCheckBox.setObjectName(_fromUtf8("byPairedClassesCheckBox"))
        self.gridLayout_2.addWidget(self.byPairedClassesCheckBox, 0, 1, 1, 1)
        self.byYearCheckBox = QtGui.QCheckBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.byYearCheckBox.setFont(font)
        self.byYearCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.byYearCheckBox.setChecked(True)
        self.byYearCheckBox.setAutoExclusive(True)
        self.byYearCheckBox.setObjectName(_fromUtf8("byYearCheckBox"))
        self.gridLayout_2.addWidget(self.byYearCheckBox, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setMargin(1)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.class0SpinBox = QtGui.QSpinBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.class0SpinBox.setFont(font)
        self.class0SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.class0SpinBox.setSuffix(_fromUtf8(""))
        self.class0SpinBox.setMaximum(87)
        self.class0SpinBox.setObjectName(_fromUtf8("class0SpinBox"))
        self.horizontalLayout_9.addWidget(self.class0SpinBox)
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setMargin(1)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.class1SpinBox = QtGui.QSpinBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.class1SpinBox.setFont(font)
        self.class1SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.class1SpinBox.setMaximum(87)
        self.class1SpinBox.setObjectName(_fromUtf8("class1SpinBox"))
        self.horizontalLayout_9.addWidget(self.class1SpinBox)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setMargin(1)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem11 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.controlSimTestDockWidget.setWidget(self.dockWidgetContents_6)
        self.horizontalLayout_14.addWidget(self.controlSimTestDockWidget)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.simTestWidgetHolder = QtGui.QWidget(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simTestWidgetHolder.sizePolicy().hasHeightForWidth())
        self.simTestWidgetHolder.setSizePolicy(sizePolicy)
        self.simTestWidgetHolder.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.simTestWidgetHolder.setFont(font)
        self.simTestWidgetHolder.setObjectName(_fromUtf8("simTestWidgetHolder"))
        self.verticalLayout_9.addWidget(self.simTestWidgetHolder)
        self.testLog = QtGui.QTextEdit(self.dockWidgetContents_5)
        self.testLog.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testLog.setFont(font)
        self.testLog.setReadOnly(True)
        self.testLog.setObjectName(_fromUtf8("testLog"))
        self.verticalLayout_9.addWidget(self.testLog)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        spacerItem13 = QtGui.QSpacerItem(14, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        self.simTestDockWidget.setWidget(self.dockWidgetContents_5)
        self.horizontalLayout_12.addWidget(self.simTestDockWidget)
        self.statsTabWidget.addTab(self.simTestTab, icon, _fromUtf8(""))
        self.xingClassTable = QtGui.QWidget()
        self.xingClassTable.setObjectName(_fromUtf8("xingClassTable"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.xingClassTable)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.crossTableDockWidget = QtGui.QDockWidget(self.xingClassTable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.crossTableDockWidget.setFont(font)
        self.crossTableDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.crossTableDockWidget.setObjectName(_fromUtf8("crossTableDockWidget"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.crossTableWidgetHolder = QtGui.QWidget(self.dockWidgetContents_4)
        self.crossTableWidgetHolder.setObjectName(_fromUtf8("crossTableWidgetHolder"))
        self.horizontalLayout_7.addWidget(self.crossTableWidgetHolder)
        self.crossTableDockWidget.setWidget(self.dockWidgetContents_4)
        self.verticalLayout_10.addWidget(self.crossTableDockWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statsTabWidget.addTab(self.xingClassTable, icon9, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.splitter_4)
        GemVisualGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GemVisualGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1388, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Open = QtGui.QMenu(self.menu_File)
        self.menu_Open.setObjectName(_fromUtf8("menu_Open"))
        self.menuGEM_Tools = QtGui.QMenu(self.menubar)
        self.menuGEM_Tools.setObjectName(_fromUtf8("menuGEM_Tools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        GemVisualGUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GemVisualGUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        GemVisualGUI.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(GemVisualGUI)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        GemVisualGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenSignatureFile = QtGui.QAction(GemVisualGUI)
        self.actionOpenSignatureFile.setCheckable(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/folder_table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenSignatureFile.setIcon(icon10)
        self.actionOpenSignatureFile.setMenuRole(QtGui.QAction.TextHeuristicRole)
        self.actionOpenSignatureFile.setObjectName(_fromUtf8("actionOpenSignatureFile"))
        self.actionOpenImageDataset = QtGui.QAction(GemVisualGUI)
        self.actionOpenImageDataset.setIcon(icon1)
        self.actionOpenImageDataset.setObjectName(_fromUtf8("actionOpenImageDataset"))
        self.actionClose = QtGui.QAction(GemVisualGUI)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/folder_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon11)
        self.actionClose.setMenuRole(QtGui.QAction.QuitRole)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionExit = QtGui.QAction(GemVisualGUI)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/silk/door_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon12)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionOpenMaskDataset = QtGui.QAction(GemVisualGUI)
        self.actionOpenMaskDataset.setIcon(icon2)
        self.actionOpenMaskDataset.setObjectName(_fromUtf8("actionOpenMaskDataset"))
        self.menu_Open.addAction(self.actionOpenSignatureFile)
        self.menu_Open.addAction(self.actionOpenImageDataset)
        self.menu_File.addAction(self.menu_Open.menuAction())
        self.menu_File.addAction(self.actionClose)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuGEM_Tools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpenSignatureFile)
        self.toolBar.addAction(self.actionOpenImageDataset)
        self.toolBar.addSeparator()
        self.label_profilesControl.setBuddy(self.gemClassSpinBox)
        self.gemYearLabel.setBuddy(self.timeSeriesComboBox)
        self.label_SPOT.setBuddy(self.timeSlider)
        self.gemClassLabel.setBuddy(self.gemClassSpinBox)
        self.label.setBuddy(self.testComboBox)
        self.label_2.setBuddy(self.pValueSpinBox)

        self.retranslateUi(GemVisualGUI)
        self.leftTabWidget.setCurrentIndex(0)
        self.rightTabWidget.setCurrentIndex(0)
        self.statsTabWidget.setCurrentIndex(0)
        self.testComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GemVisualGUI)
        GemVisualGUI.setTabOrder(self.timeSeriesComboBox, self.timeSlider)
        GemVisualGUI.setTabOrder(self.timeSlider, self.leftTabWidget)
        GemVisualGUI.setTabOrder(self.leftTabWidget, self.rightTabWidget)
        GemVisualGUI.setTabOrder(self.rightTabWidget, self.textDisplay)
        GemVisualGUI.setTabOrder(self.textDisplay, self.binSpinBox)
        GemVisualGUI.setTabOrder(self.binSpinBox, self.testComboBox)
        GemVisualGUI.setTabOrder(self.testComboBox, self.pValueSpinBox)
        GemVisualGUI.setTabOrder(self.pValueSpinBox, self.byYearCheckBox)
        GemVisualGUI.setTabOrder(self.byYearCheckBox, self.byPairedClassesCheckBox)
        GemVisualGUI.setTabOrder(self.byPairedClassesCheckBox, self.class0SpinBox)
        GemVisualGUI.setTabOrder(self.class0SpinBox, self.class1SpinBox)
        GemVisualGUI.setTabOrder(self.class1SpinBox, self.lockButton)
        GemVisualGUI.setTabOrder(self.lockButton, self.testLog)
        GemVisualGUI.setTabOrder(self.testLog, self.statsTabWidget)

    def retranslateUi(self, GemVisualGUI):
        GemVisualGUI.setWindowTitle(_translate("GemVisualGUI", "GEM Viewer", None))
        self.label_profilesControl.setText(_translate("GemVisualGUI", "NDVI-class &time series control", None))
        self.gemYearLabel.setText(_translate("GemVisualGUI", "Time series:", None))
        self.timeSeriesComboBox.setItemText(0, _translate("GemVisualGUI", "1998-1999", None))
        self.timeSeriesComboBox.setItemText(1, _translate("GemVisualGUI", "1999-2000", None))
        self.timeSeriesComboBox.setItemText(2, _translate("GemVisualGUI", "2000-2001", None))
        self.timeSeriesComboBox.setItemText(3, _translate("GemVisualGUI", "2001-2002", None))
        self.timeSeriesComboBox.setItemText(4, _translate("GemVisualGUI", "2002-2003", None))
        self.timeSeriesComboBox.setItemText(5, _translate("GemVisualGUI", "2003-2004", None))
        self.timeSeriesComboBox.setItemText(6, _translate("GemVisualGUI", "2004-2005", None))
        self.timeSeriesComboBox.setItemText(7, _translate("GemVisualGUI", "2005-2006", None))
        self.timeSeriesComboBox.setItemText(8, _translate("GemVisualGUI", "2006-2007", None))
        self.timeSeriesComboBox.setItemText(9, _translate("GemVisualGUI", "2007-2008", None))
        self.pointInTime_label.setText(_translate("GemVisualGUI", "Point in Time:", None))
        self.loadMaskButton.setText(_translate("GemVisualGUI", "Load mask", None))
        self.applyMask.setText(_translate("GemVisualGUI", "Apply mask", None))
        self.label_SPOT.setText(_translate("GemVisualGUI", "SPOT-VEGETATION NDVI 10-day synthesis time control", None))
        self.apr_label.setText(_translate("GemVisualGUI", "APR", None))
        self.may_label.setText(_translate("GemVisualGUI", "MAY", None))
        self.jun_label.setText(_translate("GemVisualGUI", "JUN", None))
        self.jul_label.setText(_translate("GemVisualGUI", "JUL", None))
        self.ago_label.setText(_translate("GemVisualGUI", "AGO", None))
        self.sep_label.setText(_translate("GemVisualGUI", "SEP", None))
        self.oct_label.setText(_translate("GemVisualGUI", "OCT", None))
        self.nov_label.setText(_translate("GemVisualGUI", "NOV", None))
        self.dec_label.setText(_translate("GemVisualGUI", "DEC", None))
        self.jan_label.setText(_translate("GemVisualGUI", "JAN", None))
        self.feb_label.setText(_translate("GemVisualGUI", "FEB", None))
        self.mar_label.setText(_translate("GemVisualGUI", "MAR", None))
        self.lockButton.setText(_translate("GemVisualGUI", "Lock", "Locks current day"))
        self.dockPlotWidget.setWindowTitle(_translate("GemVisualGUI", "Plot viewer", None))
        self.btnZoomPlot.setText(_translate("GemVisualGUI", "Zoom", None))
        self.gemClassLabel.setText(_translate("GemVisualGUI", "Class:", None))
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.plotViewerTab), _translate("GemVisualGUI", "Plot viewer", None))
        self.dockImageWidget.setWindowTitle(_translate("GemVisualGUI", "GEM Image Viewer", None))
        self.pointInTime.setText(_translate("GemVisualGUI", "1 APR 1998", None))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.imageViewerTab), _translate("GemVisualGUI", "Image viewer", None))
        self.dockFreqWidget.setWindowTitle(_translate("GemVisualGUI", "Standard deviation (SD) frequency viewer", None))
        self.label_6.setText(_translate("GemVisualGUI", "Bins:", "Select the number of bins"))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.freqViewerTab), _translate("GemVisualGUI", "Frequency viewer", None))
        self.statsTabWidget.setTabText(self.statsTabWidget.indexOf(self.logTabDisplay), _translate("GemVisualGUI", "Action Log", None))
        self.simTestDockWidget.setWindowTitle(_translate("GemVisualGUI", "Select similarity test:", None))
        self.label.setText(_translate("GemVisualGUI", "Test in use:", None))
        self.testComboBox.setItemText(0, _translate("GemVisualGUI", "Spectral angle", None))
        self.testComboBox.setItemText(1, _translate("GemVisualGUI", "Bray-Curtis distance", None))
        self.testComboBox.setItemText(2, _translate("GemVisualGUI", "Euclidian distance", None))
        self.testComboBox.setItemText(3, _translate("GemVisualGUI", "Intensity difference", None))
        self.testComboBox.setItemText(4, _translate("GemVisualGUI", "Jaccards coefficient", None))
        self.testComboBox.setItemText(5, _translate("GemVisualGUI", "Mann-Whitney u statistic", None))
        self.testComboBox.setItemText(6, _translate("GemVisualGUI", "Kolmogorov Smirnov", None))
        self.label_2.setText(_translate("GemVisualGUI", "Significance level (p)", None))
        self.label_3.setText(_translate("GemVisualGUI", "Current class", None))
        self.byPairedClassesCheckBox.setText(_translate("GemVisualGUI", "Average + standard deviation in", None))
        self.byYearCheckBox.setText(_translate("GemVisualGUI", "Averaged vs early values", None))
        self.label_4.setText(_translate("GemVisualGUI", "(", None))
        self.class0SpinBox.setPrefix(_translate("GemVisualGUI", "class ", None))
        self.label_8.setText(_translate("GemVisualGUI", ",", None))
        self.class1SpinBox.setPrefix(_translate("GemVisualGUI", "class ", None))
        self.label_7.setText(_translate("GemVisualGUI", ")", None))
        self.statsTabWidget.setTabText(self.statsTabWidget.indexOf(self.simTestTab), _translate("GemVisualGUI", "Similarity test", None))
        self.crossTableDockWidget.setWindowTitle(_translate("GemVisualGUI", "Class Crossing Table (CXT): Key Index (KI) Similarity between classes", None))
        self.statsTabWidget.setTabText(self.statsTabWidget.indexOf(self.xingClassTable), _translate("GemVisualGUI", "CXT", None))
        self.menu_File.setTitle(_translate("GemVisualGUI", "&File", None))
        self.menu_Open.setTitle(_translate("GemVisualGUI", "&Open", None))
        self.menuGEM_Tools.setTitle(_translate("GemVisualGUI", "GEM Tools", None))
        self.menuHelp.setTitle(_translate("GemVisualGUI", "Help", None))
        self.toolBar.setWindowTitle(_translate("GemVisualGUI", "toolBar", None))
        self.actionOpenSignatureFile.setText(_translate("GemVisualGUI", "Signature file", None))
        self.actionOpenSignatureFile.setToolTip(_translate("GemVisualGUI", "Open signature file", None))
        self.actionOpenImageDataset.setText(_translate("GemVisualGUI", "Image Dataset", None))
        self.actionOpenImageDataset.setToolTip(_translate("GemVisualGUI", "Open image dataset", None))
        self.actionClose.setText(_translate("GemVisualGUI", "Close files", None))
        self.actionExit.setText(_translate("GemVisualGUI", "Exit", None))
        self.actionOpenMaskDataset.setText(_translate("GemVisualGUI", "Mask Dataset", None))

import icons_rc
