# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\My Docs\working\visual\gem_viewer.ui'
#
# Created: Fri Feb 13 15:47:24 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GemVisualGUI(object):
    def setupUi(self, GemVisualGUI):
        GemVisualGUI.setObjectName("GemVisualGUI")
        GemVisualGUI.resize(1388, 1010)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/chart_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GemVisualGUI.setWindowIcon(icon)
        GemVisualGUI.setAutoFillBackground(True)
        GemVisualGUI.setStyleSheet("c")
        GemVisualGUI.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(GemVisualGUI)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.frame_2 = QtGui.QFrame(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_profilesControl = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_profilesControl.setFont(font)
        self.label_profilesControl.setObjectName("label_profilesControl")
        self.verticalLayout_15.addWidget(self.label_profilesControl)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gemYearLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.gemYearLabel.setFont(font)
        self.gemYearLabel.setObjectName("gemYearLabel")
        self.horizontalLayout.addWidget(self.gemYearLabel)
        self.timeSeriesComboBox = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSeriesComboBox.sizePolicy().hasHeightForWidth())
        self.timeSeriesComboBox.setSizePolicy(sizePolicy)
        self.timeSeriesComboBox.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.timeSeriesComboBox.setFont(font)
        self.timeSeriesComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeSeriesComboBox.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.timeSeriesComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.timeSeriesComboBox.setObjectName("timeSeriesComboBox")
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.timeSeriesComboBox.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.timeSeriesComboBox)
        self.pointInTime_label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pointInTime_label.setFont(font)
        self.pointInTime_label.setObjectName("pointInTime_label")
        self.horizontalLayout.addWidget(self.pointInTime_label)
        self.pointInTime = QtGui.QLineEdit(self.frame_2)
        self.pointInTime.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointInTime.sizePolicy().hasHeightForWidth())
        self.pointInTime.setSizePolicy(sizePolicy)
        self.pointInTime.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pointInTime.setFont(font)
        self.pointInTime.setMouseTracking(False)
        self.pointInTime.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pointInTime.setAcceptDrops(False)
        self.pointInTime.setFrame(True)
        self.pointInTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pointInTime.setObjectName("pointInTime")
        self.horizontalLayout.addWidget(self.pointInTime)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_SPOT = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_SPOT.setFont(font)
        self.label_SPOT.setObjectName("label_SPOT")
        self.verticalLayout_14.addWidget(self.label_SPOT)
        self.frameTimeSlide = QtGui.QFrame(self.frame_2)
        self.frameTimeSlide.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTimeSlide.sizePolicy().hasHeightForWidth())
        self.frameTimeSlide.setSizePolicy(sizePolicy)
        self.frameTimeSlide.setFrameShape(QtGui.QFrame.Box)
        self.frameTimeSlide.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameTimeSlide.setObjectName("frameTimeSlide")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frameTimeSlide)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.timeSlider = QtGui.QSlider(self.frameTimeSlide)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSlider.sizePolicy().hasHeightForWidth())
        self.timeSlider.setSizePolicy(sizePolicy)
        self.timeSlider.setMinimumSize(QtCore.QSize(615, 21))
        self.timeSlider.setMaximumSize(QtCore.QSize(1137, 21))
        self.timeSlider.setCursor(QtCore.Qt.ArrowCursor)
        self.timeSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeSlider.setMaximum(35)
        self.timeSlider.setSliderPosition(0)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setInvertedControls(False)
        self.timeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.timeSlider.setTickInterval(3)
        self.timeSlider.setObjectName("timeSlider")
        self.verticalLayout_8.addWidget(self.timeSlider)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtGui.QSpacerItem(5, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.apr_label = QtGui.QLabel(self.frameTimeSlide)
        self.apr_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.apr_label.setFont(font)
        self.apr_label.setScaledContents(False)
        self.apr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.apr_label.setWordWrap(False)
        self.apr_label.setObjectName("apr_label")
        self.gridLayout.addWidget(self.apr_label, 0, 1, 1, 1)
        self.may_label = QtGui.QLabel(self.frameTimeSlide)
        self.may_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.may_label.setFont(font)
        self.may_label.setScaledContents(False)
        self.may_label.setAlignment(QtCore.Qt.AlignCenter)
        self.may_label.setWordWrap(False)
        self.may_label.setObjectName("may_label")
        self.gridLayout.addWidget(self.may_label, 0, 2, 1, 1)
        self.jun_label = QtGui.QLabel(self.frameTimeSlide)
        self.jun_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.jun_label.setFont(font)
        self.jun_label.setScaledContents(False)
        self.jun_label.setAlignment(QtCore.Qt.AlignCenter)
        self.jun_label.setWordWrap(False)
        self.jun_label.setObjectName("jun_label")
        self.gridLayout.addWidget(self.jun_label, 0, 3, 1, 1)
        self.jul_label = QtGui.QLabel(self.frameTimeSlide)
        self.jul_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.jul_label.setFont(font)
        self.jul_label.setScaledContents(False)
        self.jul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.jul_label.setWordWrap(False)
        self.jul_label.setObjectName("jul_label")
        self.gridLayout.addWidget(self.jul_label, 0, 4, 1, 1)
        self.ago_label = QtGui.QLabel(self.frameTimeSlide)
        self.ago_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.ago_label.setFont(font)
        self.ago_label.setScaledContents(False)
        self.ago_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ago_label.setWordWrap(False)
        self.ago_label.setObjectName("ago_label")
        self.gridLayout.addWidget(self.ago_label, 0, 5, 1, 1)
        self.sep_label = QtGui.QLabel(self.frameTimeSlide)
        self.sep_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.sep_label.setFont(font)
        self.sep_label.setScaledContents(False)
        self.sep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sep_label.setWordWrap(False)
        self.sep_label.setObjectName("sep_label")
        self.gridLayout.addWidget(self.sep_label, 0, 6, 1, 1)
        self.oct_label = QtGui.QLabel(self.frameTimeSlide)
        self.oct_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.oct_label.setFont(font)
        self.oct_label.setScaledContents(False)
        self.oct_label.setAlignment(QtCore.Qt.AlignCenter)
        self.oct_label.setWordWrap(False)
        self.oct_label.setObjectName("oct_label")
        self.gridLayout.addWidget(self.oct_label, 0, 7, 1, 1)
        self.nov_label = QtGui.QLabel(self.frameTimeSlide)
        self.nov_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.nov_label.setFont(font)
        self.nov_label.setScaledContents(False)
        self.nov_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nov_label.setWordWrap(False)
        self.nov_label.setObjectName("nov_label")
        self.gridLayout.addWidget(self.nov_label, 0, 8, 1, 1)
        self.dec_label = QtGui.QLabel(self.frameTimeSlide)
        self.dec_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.dec_label.setFont(font)
        self.dec_label.setScaledContents(False)
        self.dec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dec_label.setWordWrap(False)
        self.dec_label.setObjectName("dec_label")
        self.gridLayout.addWidget(self.dec_label, 0, 9, 1, 1)
        self.jan_label = QtGui.QLabel(self.frameTimeSlide)
        self.jan_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.jan_label.setFont(font)
        self.jan_label.setScaledContents(False)
        self.jan_label.setAlignment(QtCore.Qt.AlignCenter)
        self.jan_label.setWordWrap(False)
        self.jan_label.setObjectName("jan_label")
        self.gridLayout.addWidget(self.jan_label, 0, 10, 1, 1)
        self.feb_label = QtGui.QLabel(self.frameTimeSlide)
        self.feb_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.feb_label.setFont(font)
        self.feb_label.setScaledContents(False)
        self.feb_label.setAlignment(QtCore.Qt.AlignCenter)
        self.feb_label.setWordWrap(False)
        self.feb_label.setObjectName("feb_label")
        self.gridLayout.addWidget(self.feb_label, 0, 11, 1, 1)
        self.mar_label = QtGui.QLabel(self.frameTimeSlide)
        self.mar_label.setMinimumSize(QtCore.QSize(45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.mar_label.setFont(font)
        self.mar_label.setScaledContents(False)
        self.mar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mar_label.setWordWrap(False)
        self.mar_label.setObjectName("mar_label")
        self.gridLayout.addWidget(self.mar_label, 0, 12, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 13, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.lockButton = QtGui.QToolButton(self.frameTimeSlide)
        self.lockButton.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lockButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/lock_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lockButton.setIcon(icon1)
        self.lockButton.setCheckable(True)
        self.lockButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.lockButton.setObjectName("lockButton")
        self.horizontalLayout_2.addWidget(self.lockButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_14.addWidget(self.frameTimeSlide)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.splitter_2 = QtGui.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 550))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftTabWidget = QtGui.QTabWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.leftTabWidget.setFont(font)
        self.leftTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.leftTabWidget.setObjectName("leftTabWidget")
        self.plotViewerTab = QtGui.QWidget()
        self.plotViewerTab.setObjectName("plotViewerTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.plotViewerTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dockPlotWidget = QtGui.QDockWidget(self.plotViewerTab)
        self.dockPlotWidget.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.dockPlotWidget.setFont(font)
        self.dockPlotWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockPlotWidget.setObjectName("dockPlotWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnZoomPlot = QtGui.QToolButton(self.dockWidgetContents)
        self.btnZoomPlot.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btnZoomPlot.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomPlot.setIcon(icon2)
        self.btnZoomPlot.setIconSize(QtCore.QSize(24, 24))
        self.btnZoomPlot.setCheckable(True)
        self.btnZoomPlot.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnZoomPlot.setObjectName("btnZoomPlot")
        self.horizontalLayout_5.addWidget(self.btnZoomPlot)
        self.gemClassLabel = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.gemClassLabel.setFont(font)
        self.gemClassLabel.setObjectName("gemClassLabel")
        self.horizontalLayout_5.addWidget(self.gemClassLabel)
        self.gemClassSpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.gemClassSpinBox.setFont(font)
        self.gemClassSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gemClassSpinBox.setMinimum(0)
        self.gemClassSpinBox.setMaximum(86)
        self.gemClassSpinBox.setProperty("value", QtCore.QVariant(0))
        self.gemClassSpinBox.setObjectName("gemClassSpinBox")
        self.horizontalLayout_5.addWidget(self.gemClassSpinBox)
        spacerItem5 = QtGui.QSpacerItem(468, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.plotWidgetHolder = QtGui.QWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidgetHolder.sizePolicy().hasHeightForWidth())
        self.plotWidgetHolder.setSizePolicy(sizePolicy)
        self.plotWidgetHolder.setMinimumSize(QtCore.QSize(0, 375))
        self.plotWidgetHolder.setObjectName("plotWidgetHolder")
        self.verticalLayout.addWidget(self.plotWidgetHolder)
        self.dockPlotWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout_2.addWidget(self.dockPlotWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/chart_curve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftTabWidget.addTab(self.plotViewerTab, icon3, "")
        self.rightTabWidget = QtGui.QTabWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.rightTabWidget.setFont(font)
        self.rightTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.rightTabWidget.setObjectName("rightTabWidget")
        self.imageViewerTab = QtGui.QWidget()
        self.imageViewerTab.setObjectName("imageViewerTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.imageViewerTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dockImageWidget = QtGui.QDockWidget(self.imageViewerTab)
        self.dockImageWidget.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.dockImageWidget.setFont(font)
        self.dockImageWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockImageWidget.setObjectName("dockImageWidget")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.loadMaskButton = QtGui.QToolButton(self.dockWidgetContents_2)
        self.loadMaskButton.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.loadMaskButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/folder_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadMaskButton.setIcon(icon4)
        self.loadMaskButton.setCheckable(True)
        self.loadMaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.loadMaskButton.setObjectName("loadMaskButton")
        self.horizontalLayout_6.addWidget(self.loadMaskButton)
        self.applyMask = QtGui.QToolButton(self.dockWidgetContents_2)
        self.applyMask.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.applyMask.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/shape_move_forwards.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyMask.setIcon(icon5)
        self.applyMask.setIconSize(QtCore.QSize(24, 24))
        self.applyMask.setCheckable(True)
        self.applyMask.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.applyMask.setObjectName("applyMask")
        self.horizontalLayout_6.addWidget(self.applyMask)
        spacerItem6 = QtGui.QSpacerItem(498, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.imageWidgetHolder = QtGui.QWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageWidgetHolder.sizePolicy().hasHeightForWidth())
        self.imageWidgetHolder.setSizePolicy(sizePolicy)
        self.imageWidgetHolder.setMinimumSize(QtCore.QSize(0, 405))
        self.imageWidgetHolder.setObjectName("imageWidgetHolder")
        self.verticalLayout_3.addWidget(self.imageWidgetHolder)
        self.dockImageWidget.setWidget(self.dockWidgetContents_2)
        self.verticalLayout_4.addWidget(self.dockImageWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTabWidget.addTab(self.imageViewerTab, icon6, "")
        self.freqViewerTab = QtGui.QWidget()
        self.freqViewerTab.setObjectName("freqViewerTab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.freqViewerTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dockFreqWidget = QtGui.QDockWidget(self.freqViewerTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.dockFreqWidget.setFont(font)
        self.dockFreqWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockFreqWidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockFreqWidget.setObjectName("dockFreqWidget")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.binSpinBox = QtGui.QSpinBox(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.binSpinBox.setFont(font)
        self.binSpinBox.setMinimum(2)
        self.binSpinBox.setMaximum(50)
        self.binSpinBox.setSingleStep(1)
        self.binSpinBox.setProperty("value", QtCore.QVariant(10))
        self.binSpinBox.setObjectName("binSpinBox")
        self.horizontalLayout_8.addWidget(self.binSpinBox)
        spacerItem7 = QtGui.QSpacerItem(38, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.freqWidgetHolder = QtGui.QWidget(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqWidgetHolder.sizePolicy().hasHeightForWidth())
        self.freqWidgetHolder.setSizePolicy(sizePolicy)
        self.freqWidgetHolder.setMinimumSize(QtCore.QSize(0, 375))
        self.freqWidgetHolder.setObjectName("freqWidgetHolder")
        self.verticalLayout_5.addWidget(self.freqWidgetHolder)
        self.dockFreqWidget.setWidget(self.dockWidgetContents_3)
        self.verticalLayout_7.addWidget(self.dockFreqWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/chart_bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTabWidget.addTab(self.freqViewerTab, icon7, "")
        self.statsTabWidget = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsTabWidget.sizePolicy().hasHeightForWidth())
        self.statsTabWidget.setSizePolicy(sizePolicy)
        self.statsTabWidget.setMinimumSize(QtCore.QSize(0, 225))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.statsTabWidget.setFont(font)
        self.statsTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.statsTabWidget.setObjectName("statsTabWidget")
        self.logTabDisplay = QtGui.QWidget()
        self.logTabDisplay.setObjectName("logTabDisplay")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.logTabDisplay)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textDisplay = QtGui.QTextEdit(self.logTabDisplay)
        self.textDisplay.setObjectName("textDisplay")
        self.verticalLayout_6.addWidget(self.textDisplay)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/book_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statsTabWidget.addTab(self.logTabDisplay, icon8, "")
        self.simTestTab = QtGui.QWidget()
        self.simTestTab.setObjectName("simTestTab")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.simTestTab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.simTestDockWidget = QtGui.QDockWidget(self.simTestTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simTestDockWidget.sizePolicy().hasHeightForWidth())
        self.simTestDockWidget.setSizePolicy(sizePolicy)
        self.simTestDockWidget.setMinimumSize(QtCore.QSize(0, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.simTestDockWidget.setFont(font)
        self.simTestDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.simTestDockWidget.setObjectName("simTestDockWidget")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.controlSimTestDockWidget = QtGui.QDockWidget(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlSimTestDockWidget.sizePolicy().hasHeightForWidth())
        self.controlSimTestDockWidget.setSizePolicy(sizePolicy)
        self.controlSimTestDockWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.controlSimTestDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.controlSimTestDockWidget.setObjectName("controlSimTestDockWidget")
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.testComboBox = QtGui.QComboBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.testComboBox.setFont(font)
        self.testComboBox.setObjectName("testComboBox")
        self.testComboBox.addItem(QtCore.QString())
        self.testComboBox.addItem(QtCore.QString())
        self.testComboBox.addItem(QtCore.QString())
        self.testComboBox.addItem(QtCore.QString())
        self.testComboBox.addItem(QtCore.QString())
        self.testComboBox.addItem(QtCore.QString())
        self.testComboBox.addItem(QtCore.QString())
        self.horizontalLayout_10.addWidget(self.testComboBox)
        spacerItem8 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.pValueSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pValueSpinBox.setFont(font)
        self.pValueSpinBox.setMaximum(1.0)
        self.pValueSpinBox.setSingleStep(0.01)
        self.pValueSpinBox.setProperty("value", QtCore.QVariant(0.95))
        self.pValueSpinBox.setObjectName("pValueSpinBox")
        self.horizontalLayout_10.addWidget(self.pValueSpinBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.byPairedClassesCheckBox = QtGui.QCheckBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.byPairedClassesCheckBox.setFont(font)
        self.byPairedClassesCheckBox.setAutoExclusive(True)
        self.byPairedClassesCheckBox.setObjectName("byPairedClassesCheckBox")
        self.gridLayout_2.addWidget(self.byPairedClassesCheckBox, 0, 1, 1, 1)
        self.byYearCheckBox = QtGui.QCheckBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.byYearCheckBox.setFont(font)
        self.byYearCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.byYearCheckBox.setChecked(True)
        self.byYearCheckBox.setAutoExclusive(True)
        self.byYearCheckBox.setObjectName("byYearCheckBox")
        self.gridLayout_2.addWidget(self.byYearCheckBox, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setMargin(1)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.class0SpinBox = QtGui.QSpinBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.class0SpinBox.setFont(font)
        self.class0SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.class0SpinBox.setMaximum(87)
        self.class0SpinBox.setObjectName("class0SpinBox")
        self.horizontalLayout_9.addWidget(self.class0SpinBox)
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setMargin(1)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.class1SpinBox = QtGui.QSpinBox(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.class1SpinBox.setFont(font)
        self.class1SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.class1SpinBox.setMaximum(87)
        self.class1SpinBox.setObjectName("class1SpinBox")
        self.horizontalLayout_9.addWidget(self.class1SpinBox)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setMargin(1)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem11 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.controlSimTestDockWidget.setWidget(self.dockWidgetContents_6)
        self.horizontalLayout_14.addWidget(self.controlSimTestDockWidget)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.simTestWidgetHolder = QtGui.QWidget(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simTestWidgetHolder.sizePolicy().hasHeightForWidth())
        self.simTestWidgetHolder.setSizePolicy(sizePolicy)
        self.simTestWidgetHolder.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.simTestWidgetHolder.setFont(font)
        self.simTestWidgetHolder.setObjectName("simTestWidgetHolder")
        self.verticalLayout_9.addWidget(self.simTestWidgetHolder)
        self.testLog = QtGui.QTextEdit(self.dockWidgetContents_5)
        self.testLog.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.testLog.setFont(font)
        self.testLog.setReadOnly(True)
        self.testLog.setObjectName("testLog")
        self.verticalLayout_9.addWidget(self.testLog)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        spacerItem13 = QtGui.QSpacerItem(14, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        self.simTestDockWidget.setWidget(self.dockWidgetContents_5)
        self.horizontalLayout_12.addWidget(self.simTestDockWidget)
        self.statsTabWidget.addTab(self.simTestTab, icon, "")
        self.xingClassTable = QtGui.QWidget()
        self.xingClassTable.setObjectName("xingClassTable")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.xingClassTable)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.crossTableDockWidget = QtGui.QDockWidget(self.xingClassTable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.crossTableDockWidget.setFont(font)
        self.crossTableDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.crossTableDockWidget.setObjectName("crossTableDockWidget")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.crossTableWidgetHolder = QtGui.QWidget(self.dockWidgetContents_4)
        self.crossTableWidgetHolder.setObjectName("crossTableWidgetHolder")
        self.horizontalLayout_7.addWidget(self.crossTableWidgetHolder)
        self.crossTableDockWidget.setWidget(self.dockWidgetContents_4)
        self.verticalLayout_10.addWidget(self.crossTableDockWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statsTabWidget.addTab(self.xingClassTable, icon9, "")
        self.verticalLayout_16.addWidget(self.splitter_4)
        GemVisualGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GemVisualGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1388, 19))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Open = QtGui.QMenu(self.menu_File)
        self.menu_Open.setObjectName("menu_Open")
        self.menuGEM_Tools = QtGui.QMenu(self.menubar)
        self.menuGEM_Tools.setObjectName("menuGEM_Tools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        GemVisualGUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GemVisualGUI)
        self.statusbar.setObjectName("statusbar")
        GemVisualGUI.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(GemVisualGUI)
        self.toolBar.setObjectName("toolBar")
        GemVisualGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenSignatureFile = QtGui.QAction(GemVisualGUI)
        self.actionOpenSignatureFile.setCheckable(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/folder_table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenSignatureFile.setIcon(icon10)
        self.actionOpenSignatureFile.setMenuRole(QtGui.QAction.TextHeuristicRole)
        self.actionOpenSignatureFile.setObjectName("actionOpenSignatureFile")
        self.actionOpenImageDataset = QtGui.QAction(GemVisualGUI)
        self.actionOpenImageDataset.setIcon(icon4)
        self.actionOpenImageDataset.setObjectName("actionOpenImageDataset")
        self.actionClose = QtGui.QAction(GemVisualGUI)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/folder_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon11)
        self.actionClose.setMenuRole(QtGui.QAction.QuitRole)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtGui.QAction(GemVisualGUI)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/icons/silk/door_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon12)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenMaskDataset = QtGui.QAction(GemVisualGUI)
        self.actionOpenMaskDataset.setIcon(icon5)
        self.actionOpenMaskDataset.setObjectName("actionOpenMaskDataset")
        self.menu_Open.addAction(self.actionOpenSignatureFile)
        self.menu_Open.addAction(self.actionOpenImageDataset)
        self.menu_File.addAction(self.menu_Open.menuAction())
        self.menu_File.addAction(self.actionClose)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuGEM_Tools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpenSignatureFile)
        self.toolBar.addAction(self.actionOpenImageDataset)
        self.toolBar.addSeparator()
        self.label_profilesControl.setBuddy(self.gemClassSpinBox)
        self.gemYearLabel.setBuddy(self.timeSeriesComboBox)
        self.label_SPOT.setBuddy(self.timeSlider)
        self.gemClassLabel.setBuddy(self.gemClassSpinBox)
        self.label.setBuddy(self.testComboBox)
        self.label_2.setBuddy(self.pValueSpinBox)

        self.retranslateUi(GemVisualGUI)
        self.leftTabWidget.setCurrentIndex(0)
        self.rightTabWidget.setCurrentIndex(0)
        self.statsTabWidget.setCurrentIndex(0)
        self.testComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GemVisualGUI)
        GemVisualGUI.setTabOrder(self.timeSeriesComboBox, self.timeSlider)
        GemVisualGUI.setTabOrder(self.timeSlider, self.leftTabWidget)
        GemVisualGUI.setTabOrder(self.leftTabWidget, self.rightTabWidget)
        GemVisualGUI.setTabOrder(self.rightTabWidget, self.loadMaskButton)
        GemVisualGUI.setTabOrder(self.loadMaskButton, self.applyMask)
        GemVisualGUI.setTabOrder(self.applyMask, self.textDisplay)
        GemVisualGUI.setTabOrder(self.textDisplay, self.binSpinBox)
        GemVisualGUI.setTabOrder(self.binSpinBox, self.testComboBox)
        GemVisualGUI.setTabOrder(self.testComboBox, self.pValueSpinBox)
        GemVisualGUI.setTabOrder(self.pValueSpinBox, self.byYearCheckBox)
        GemVisualGUI.setTabOrder(self.byYearCheckBox, self.byPairedClassesCheckBox)
        GemVisualGUI.setTabOrder(self.byPairedClassesCheckBox, self.class0SpinBox)
        GemVisualGUI.setTabOrder(self.class0SpinBox, self.class1SpinBox)
        GemVisualGUI.setTabOrder(self.class1SpinBox, self.lockButton)
        GemVisualGUI.setTabOrder(self.lockButton, self.testLog)
        GemVisualGUI.setTabOrder(self.testLog, self.statsTabWidget)

    def retranslateUi(self, GemVisualGUI):
        GemVisualGUI.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "GEM Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_profilesControl.setText(QtGui.QApplication.translate("GemVisualGUI", "NDVI-class &time series control", None, QtGui.QApplication.UnicodeUTF8))
        self.gemYearLabel.setText(QtGui.QApplication.translate("GemVisualGUI", "Time series:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(0, QtGui.QApplication.translate("GemVisualGUI", "1998-1999", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(1, QtGui.QApplication.translate("GemVisualGUI", "1999-2000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(2, QtGui.QApplication.translate("GemVisualGUI", "2000-2001", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(3, QtGui.QApplication.translate("GemVisualGUI", "2001-2002", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(4, QtGui.QApplication.translate("GemVisualGUI", "2002-2003", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(5, QtGui.QApplication.translate("GemVisualGUI", "2003-2004", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(6, QtGui.QApplication.translate("GemVisualGUI", "2004-2005", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(7, QtGui.QApplication.translate("GemVisualGUI", "2005-2006", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(8, QtGui.QApplication.translate("GemVisualGUI", "2006-2007", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeriesComboBox.setItemText(9, QtGui.QApplication.translate("GemVisualGUI", "2007-2008", None, QtGui.QApplication.UnicodeUTF8))
        self.pointInTime_label.setText(QtGui.QApplication.translate("GemVisualGUI", "Point in Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.pointInTime.setText(QtGui.QApplication.translate("GemVisualGUI", "1 APR 1998", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SPOT.setText(QtGui.QApplication.translate("GemVisualGUI", "SPOT-VEGETATION NDVI 10-day synthesis time control", None, QtGui.QApplication.UnicodeUTF8))
        self.apr_label.setText(QtGui.QApplication.translate("GemVisualGUI", "APR", None, QtGui.QApplication.UnicodeUTF8))
        self.may_label.setText(QtGui.QApplication.translate("GemVisualGUI", "MAY", None, QtGui.QApplication.UnicodeUTF8))
        self.jun_label.setText(QtGui.QApplication.translate("GemVisualGUI", "JUN", None, QtGui.QApplication.UnicodeUTF8))
        self.jul_label.setText(QtGui.QApplication.translate("GemVisualGUI", "JUL", None, QtGui.QApplication.UnicodeUTF8))
        self.ago_label.setText(QtGui.QApplication.translate("GemVisualGUI", "AGO", None, QtGui.QApplication.UnicodeUTF8))
        self.sep_label.setText(QtGui.QApplication.translate("GemVisualGUI", "SEP", None, QtGui.QApplication.UnicodeUTF8))
        self.oct_label.setText(QtGui.QApplication.translate("GemVisualGUI", "OCT", None, QtGui.QApplication.UnicodeUTF8))
        self.nov_label.setText(QtGui.QApplication.translate("GemVisualGUI", "NOV", None, QtGui.QApplication.UnicodeUTF8))
        self.dec_label.setText(QtGui.QApplication.translate("GemVisualGUI", "DEC", None, QtGui.QApplication.UnicodeUTF8))
        self.jan_label.setText(QtGui.QApplication.translate("GemVisualGUI", "JAN", None, QtGui.QApplication.UnicodeUTF8))
        self.feb_label.setText(QtGui.QApplication.translate("GemVisualGUI", "FEB", None, QtGui.QApplication.UnicodeUTF8))
        self.mar_label.setText(QtGui.QApplication.translate("GemVisualGUI", "MAR", None, QtGui.QApplication.UnicodeUTF8))
        self.lockButton.setText(QtGui.QApplication.translate("GemVisualGUI", "Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.dockPlotWidget.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "Plot viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomPlot.setText(QtGui.QApplication.translate("GemVisualGUI", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.gemClassLabel.setText(QtGui.QApplication.translate("GemVisualGUI", "Class:", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.plotViewerTab), QtGui.QApplication.translate("GemVisualGUI", "Plot viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.dockImageWidget.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "Image viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.loadMaskButton.setText(QtGui.QApplication.translate("GemVisualGUI", "Load mask", None, QtGui.QApplication.UnicodeUTF8))
        self.applyMask.setText(QtGui.QApplication.translate("GemVisualGUI", "Apply mask", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.imageViewerTab), QtGui.QApplication.translate("GemVisualGUI", "Image viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.dockFreqWidget.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "Standard deviation (SD) frequency viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GemVisualGUI", "Bins:", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.freqViewerTab), QtGui.QApplication.translate("GemVisualGUI", "Frequency viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.statsTabWidget.setTabText(self.statsTabWidget.indexOf(self.logTabDisplay), QtGui.QApplication.translate("GemVisualGUI", "Action Log", None, QtGui.QApplication.UnicodeUTF8))
        self.simTestDockWidget.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "Select similarity test:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GemVisualGUI", "Test in use:", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(0, QtGui.QApplication.translate("GemVisualGUI", "Spectral angle", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(1, QtGui.QApplication.translate("GemVisualGUI", "Bray-Curtis distance", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(2, QtGui.QApplication.translate("GemVisualGUI", "Euclidian distance", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(3, QtGui.QApplication.translate("GemVisualGUI", "Intensity difference", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(4, QtGui.QApplication.translate("GemVisualGUI", "Jaccards coefficient", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(5, QtGui.QApplication.translate("GemVisualGUI", "Mann-Whitney u statistic", None, QtGui.QApplication.UnicodeUTF8))
        self.testComboBox.setItemText(6, QtGui.QApplication.translate("GemVisualGUI", "Kolmogorov Smirnov", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GemVisualGUI", "Significance level (p)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GemVisualGUI", "Current class", None, QtGui.QApplication.UnicodeUTF8))
        self.byPairedClassesCheckBox.setText(QtGui.QApplication.translate("GemVisualGUI", "Average + standard deviation in", None, QtGui.QApplication.UnicodeUTF8))
        self.byYearCheckBox.setText(QtGui.QApplication.translate("GemVisualGUI", "Averaged vs early values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GemVisualGUI", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.class0SpinBox.setPrefix(QtGui.QApplication.translate("GemVisualGUI", "class ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GemVisualGUI", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.class1SpinBox.setPrefix(QtGui.QApplication.translate("GemVisualGUI", "class ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GemVisualGUI", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.statsTabWidget.setTabText(self.statsTabWidget.indexOf(self.simTestTab), QtGui.QApplication.translate("GemVisualGUI", "Similarity test", None, QtGui.QApplication.UnicodeUTF8))
        self.crossTableDockWidget.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "Class Crossing Table (CXT): Beltran-deBie Index", None, QtGui.QApplication.UnicodeUTF8))
        self.statsTabWidget.setTabText(self.statsTabWidget.indexOf(self.xingClassTable), QtGui.QApplication.translate("GemVisualGUI", "CXT", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("GemVisualGUI", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Open.setTitle(QtGui.QApplication.translate("GemVisualGUI", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGEM_Tools.setTitle(QtGui.QApplication.translate("GemVisualGUI", "GEM Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("GemVisualGUI", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("GemVisualGUI", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSignatureFile.setText(QtGui.QApplication.translate("GemVisualGUI", "Signature file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSignatureFile.setToolTip(QtGui.QApplication.translate("GemVisualGUI", "Open signature file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenImageDataset.setText(QtGui.QApplication.translate("GemVisualGUI", "Image Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenImageDataset.setToolTip(QtGui.QApplication.translate("GemVisualGUI", "Open image dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("GemVisualGUI", "Close files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("GemVisualGUI", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenMaskDataset.setText(QtGui.QApplication.translate("GemVisualGUI", "Mask Dataset", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
